<?php
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals -- Existing public UCP API/drop-in symbols are intentionally preserved for backward compatibility.
if (!defined('ABSPATH')) {
    exit;
}

trait UCP_Cache_Storage_Trait {
    /**
     * Acquire a per-representation filesystem lock before publishing a cache generation.
     *
     * The lock serializes concurrent misses for the same cache path. Lock files are kept in the
     * plugin-owned cache directory so waiting processes always refer to the same inode.
     *
     * @param string $path Cache representation path.
     * @return resource|false
     */
    private function acquire_cache_write_lock($path) {
        $lock_dir = trailingslashit(UCP_CACHE_DIR) . 'locks/';
        if (!is_dir($lock_dir)) {
            wp_mkdir_p($lock_dir);
        }
        if (!is_dir($lock_dir) || !wp_is_writable($lock_dir)) {
            return false;
        }

        // Use a bounded 4096-slot lock pool: 256 shards with 16 stable lock files each.
        // The same representation always maps to the same slot, while unrelated cache keys
        // can occasionally serialize instead of leaving an unbounded historic lock namespace.
        $lock_hash = hash('sha256', wp_normalize_path((string) $path));
        $lock_subdir = $lock_dir . substr($lock_hash, 0, 2) . '/';
        if (!is_dir($lock_subdir)) {
            wp_mkdir_p($lock_subdir);
        }
        if (!is_dir($lock_subdir) || !wp_is_writable($lock_subdir)) {
            return false;
        }
        $lock_path = $lock_subdir . substr($lock_hash, 2, 1) . '.lock';
        $handle = UCP_Helpers::open_managed_cache_file($lock_path, 'c');
        if (!is_resource($handle)) {
            return false;
        }

        $wait_ms = max(25, min(1000, absint(apply_filters('ucp_cache_write_lock_wait_ms', 250, $path))));
        $deadline = microtime(true) + ($wait_ms / 1000);
        do {
            // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_flock -- bounded per-cache-key writer serialization.
            if (@flock($handle, LOCK_EX | LOCK_NB)) {
                return $handle;
            }
            usleep(10000); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.system_calls_usleep -- short bounded lock backoff.
        } while (microtime(true) < $deadline);

        fclose($handle); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose
        return false;
    }

    /**
     * Release a cache writer lock.
     *
     * @param resource|false $handle Lock handle.
     * @return void
     */
    private function release_cache_write_lock($handle) {
        if (!is_resource($handle)) {
            return;
        }
        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_flock -- release the plugin-owned cache writer lock.
        @flock($handle, LOCK_UN);
        fclose($handle); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose
    }

    /**
     * Normalize response headers that are safe and meaningful to replay with cached HTML.
     * Cache-control, cookies, validators and transport headers are generated by UltraCache
     * or deliberately excluded; invariant security/representation headers are preserved.
     *
     * @param array $headers Raw header lines.
     * @return array<int,string>
     */
    private function normalize_page_cache_response_headers($headers) {
        if (!is_array($headers)) {
            return array();
        }
        $allowed = array_fill_keys(array(
            'content-language',
            'content-security-policy',
            'content-security-policy-report-only',
            'cross-origin-embedder-policy',
            'cross-origin-opener-policy',
            'cross-origin-resource-policy',
            'document-policy',
            'link',
            'nel',
            'origin-agent-cluster',
            'permissions-policy',
            'referrer-policy',
            'report-to',
            'reporting-endpoints',
            'strict-transport-security',
            'x-content-type-options',
            'x-dns-prefetch-control',
            'x-download-options',
            'x-frame-options',
            'x-permitted-cross-domain-policies',
            'x-robots-tag',
            'x-xss-protection',
        ), true);
        $normalized = array();
        $bytes = 0;
        foreach (array_slice($headers, 0, 64) as $header_line) {
            if (!is_scalar($header_line)) {
                continue;
            }
            $header_line = trim((string) $header_line);
            if ('' === $header_line || strlen($header_line) > 4096 || false !== strpbrk($header_line, "\r\n\0")) {
                continue;
            }
            if (1 !== preg_match('/^([!#$%&\'*+.^_`|~0-9A-Za-z-]+)\s*:\s*(.*)$/', $header_line, $match)) {
                continue;
            }
            $name = strtolower($match[1]);
            $value = trim($match[2]);
            if (!isset($allowed[$name]) || '' === $value || preg_match('/[\x00-\x08\x0A-\x1F\x7F]/', $value)) {
                continue;
            }
            $line = $match[1] . ': ' . $value;
            $bytes += strlen($line);
            if ($bytes > 8192) {
                break;
            }
            $normalized[] = $line;
        }
        return $normalized;
    }

    /**
     * Capture cache-safe origin headers before WordPress is bypassed on future HITs.
     *
     * @return array<int,string>
     */
    private function capture_page_cache_response_headers() {
        return $this->normalize_page_cache_response_headers(headers_list());
    }

    /**
     * Replay validated origin headers for PHP-fallback cache HITs.
     *
     * @param array $headers Stored response headers.
     * @return void
     */
    private function send_cached_page_response_headers($headers) {
        foreach ($this->normalize_page_cache_response_headers($headers) as $header_line) {
            header($header_line, false);
        }
    }

    /**
     * Publish identity HTML and its compressed siblings as one coherent cache generation.
     *
     * @param string $path Cache file path.
     * @param string $html HTML response.
     * @return bool
     */
    private function write_cache_representation($path, $html, $metadata) {
        $lock = $this->acquire_cache_write_lock($path);
        if (!is_resource($lock)) {
            UCP_Diagnostics::record('cache', 'Skipped cache write because the cache-key lock was unavailable', array('file' => basename((string) $path)));
            return false;
        }

        $path = (string) $path;
        $html = (string) $html;
        $metadata = is_array($metadata) ? $metadata : array();
        $metadata['content_sha256'] = hash('sha256', $html);
        $meta_json = UCP_Helpers::safe_json_encode($metadata);
        if ('' === $path || '' === $html || !is_string($meta_json) || '' === $meta_json) {
            $this->release_cache_write_lock($lock);
            return false;
        }

        $suffix = wp_generate_password(12, false, false);
        $meta_path = $path . '.meta.json';
        $stage_html = $path . '.ucp-stage-' . $suffix;
        $stage_meta = $meta_path . '.ucp-stage-' . $suffix;
        $rollback_html = $path . '.ucp-rollback-' . $suffix;
        $rollback_meta = $meta_path . '.ucp-rollback-' . $suffix;
        $had_html = is_file($path);
        $had_meta = is_file($meta_path);

        $cleanup = static function($files) {
            foreach ((array) $files as $file) {
                UCP_Helpers::safe_delete_file($file);
            }
        };
        $restore = static function() use ($path, $meta_path, $rollback_html, $rollback_meta, $had_html, $had_meta, $cleanup) {
            // Never delete an original generation unless its rollback copy exists.
            if ($had_meta && is_file($rollback_meta)) {
                UCP_Helpers::safe_delete_file($meta_path);
                UCP_Helpers::move_file($rollback_meta, $meta_path);
            } elseif (!$had_meta) {
                UCP_Helpers::safe_delete_file($meta_path);
            }
            if ($had_html && is_file($rollback_html)) {
                UCP_Helpers::safe_delete_file($path);
                UCP_Helpers::move_file($rollback_html, $path);
            } elseif (!$had_html) {
                UCP_Helpers::safe_delete_file($path);
            }
            $cleanup(array($rollback_html, $rollback_meta));
        };

        $identity_published = false;
        try {
            $cleanup(array($stage_html, $stage_meta, $rollback_html, $rollback_meta));
            if (!UCP_Helpers::write_file_atomic($stage_html, $html)
                || !UCP_Helpers::write_file_atomic($stage_meta, $meta_json)) {
                $cleanup(array($stage_html, $stage_meta));
                return false;
            }

            $staged_html = is_readable($stage_html) ? UCP_Helpers::read_file($stage_html, 20 * MB_IN_BYTES) : '';
            $staged_meta = is_readable($stage_meta) ? UCP_Helpers::read_file($stage_meta, 64 * KB_IN_BYTES) : '';
            if (!is_string($staged_html) || !is_string($staged_meta)
                || !hash_equals(hash('sha256', $html), hash('sha256', $staged_html))
                || !hash_equals(hash('sha256', $meta_json), hash('sha256', $staged_meta))) {
                $cleanup(array($stage_html, $stage_meta));
                return false;
            }

            if ($had_html && !UCP_Helpers::move_file($path, $rollback_html)) {
                $cleanup(array($stage_html, $stage_meta));
                return false;
            }
            if ($had_meta && !UCP_Helpers::move_file($meta_path, $rollback_meta)) {
                if ($had_html && is_file($rollback_html)) {
                    UCP_Helpers::move_file($rollback_html, $path);
                }
                $cleanup(array($stage_html, $stage_meta, $rollback_meta));
                return false;
            }

            // The active HTML is intentionally absent while metadata is activated. Readers
            // therefore miss safely instead of observing HTML with metadata from another generation.
            // Existing compressed siblings remain until the identity generation is verified. The
            // early drop-in rejects stale siblings by mtime, so they cannot be served cross-generation.
            if (!UCP_Helpers::move_file($stage_meta, $meta_path)
                || !UCP_Helpers::move_file($stage_html, $path)) {
                $restore();
                $cleanup(array($stage_html, $stage_meta, $rollback_html, $rollback_meta));
                return false;
            }

            $active_html = is_readable($path) ? UCP_Helpers::read_file($path, 20 * MB_IN_BYTES) : '';
            $active_meta = is_readable($meta_path) ? UCP_Helpers::read_file($meta_path, 64 * KB_IN_BYTES) : '';
            if (!is_string($active_html) || !is_string($active_meta)
                || !hash_equals(hash('sha256', $html), hash('sha256', $active_html))
                || !hash_equals(hash('sha256', $meta_json), hash('sha256', $active_meta))) {
                $restore();
                $cleanup(array($stage_html, $stage_meta, $rollback_html, $rollback_meta));
                return false;
            }

            $identity_published = true;
            $cleanup(array($rollback_html, $rollback_meta));

            // Compressed siblings are optional derivatives. Once identity HTML and
            // metadata are verified, a compressor failure must not invalidate or
            // misreport the successfully published cache generation.
            try {
                UCP_Helpers::safe_delete_file($path . '.gz');
                UCP_Helpers::safe_delete_file($path . '.br');
                if (!$this->queue_precompressed_cache_variants($path, $metadata['content_sha256'])) {
                    $this->write_precompressed_cache_variants($path, $html);
                }
            } catch (Throwable $compression_exception) {
                UCP_Helpers::safe_delete_file($path . '.gz');
                UCP_Helpers::safe_delete_file($path . '.br');
                if (class_exists('UCP_Diagnostics')) {
                    UCP_Diagnostics::record('cache', 'Optional cache precompression failed after identity publication.', array(
                        'path_hash' => hash('sha256', wp_normalize_path($path)),
                        'exception' => sanitize_key(get_class($compression_exception)),
                        'code'      => (string) $compression_exception->getCode(),
                    ));
                }
            }
            return true;
        } catch (Throwable $e) {
            if (!$identity_published) {
                $restore();
            }
            if (class_exists('UCP_Diagnostics')) {
                UCP_Diagnostics::record('cache', $identity_published ? 'Post-publication cache cleanup failed safely.' : 'Cache publication was rolled back after an exception.', array(
                    'path_hash' => hash('sha256', wp_normalize_path($path)),
                    'exception' => sanitize_key(get_class($e)),
                    'code'      => (string) $e->getCode(),
                ));
            }
            return $identity_published;
        } finally {
            $cleanup(array($stage_html, $stage_meta, $rollback_html, $rollback_meta));
            $this->release_cache_write_lock($lock);
        }
    }

    private function cap_private_user_cache_lifetime($ttl, $stale_ttl) {
        $ttl = max(0, (int) $ttl);
        $stale_ttl = max(0, (int) $stale_ttl);
        if (!function_exists('is_user_logged_in') || !is_user_logged_in()) {
            return array('ttl' => $ttl, 'stale' => $stale_ttl);
        }

        $nonce_life = function_exists('apply_filters')
            ? max(MINUTE_IN_SECONDS, (int) apply_filters('nonce_life', DAY_IN_SECONDS, -1))
            : DAY_IN_SECONDS;
        $safe_ttl = max(MINUTE_IN_SECONDS, (int) floor($nonce_life / 2) - (5 * MINUTE_IN_SECONDS));
        if (0 === $ttl || $ttl > $safe_ttl) {
            $ttl = $safe_ttl;
        }
        return array('ttl' => $ttl, 'stale' => 0);
    }

    public function maybe_serve_cache() {
        if (class_exists('UCP_LiteSpeed_Cache') && UCP_LiteSpeed_Cache::should_bypass_disk_page_cache()) {
            return;
        }

        if (!$this->can_cache_request()) {
            $this->maybe_send_cache_debug_header('bypass', $this->bypass_reason);
            return;
        }
        $file = UCP_Helpers::cache_file_path();
        $policy = $this->cache_policy_decision(UCP_Options::get_all());
        $ttl = isset($policy['ttl']) ? absint($policy['ttl']) : absint(UCP_Options::get('cache_lifespan', 10)) * HOUR_IN_SECONDS;
        $stale_ttl = isset($policy['stale']) ? absint($policy['stale']) : absint(UCP_Options::get('stale_cache_lifespan', 24)) * HOUR_IN_SECONDS;

        // Per-generation metadata is authoritative. This keeps the PHP fallback aligned
        // with advanced-cache.php when a writer deliberately caps a representation TTL.
        $meta_file = $file . '.meta.json';
        if (UCP_Helpers::is_safe_managed_cache_file($meta_file)) {
            $meta_size = filesize($meta_file);
            if (false !== $meta_size && $meta_size > 0 && $meta_size <= 16384) {
                $meta = UCP_Helpers::safe_json_decode(UCP_Helpers::read_file($meta_file, 64 * KB_IN_BYTES), true);
                if (is_array($meta) && array_key_exists('ttl', $meta)) {
                    $ttl = min(YEAR_IN_SECONDS, max(0, (int) $meta['ttl']));
                }
                if (is_array($meta) && array_key_exists('stale', $meta)) {
                    $stale_ttl = min(YEAR_IN_SECONDS, max(0, (int) $meta['stale']));
                }
            }
        }

        $private_lifetime = $this->cap_private_user_cache_lifetime($ttl, $stale_ttl);
        $ttl = $private_lifetime['ttl'];
        $stale_ttl = $private_lifetime['stale'];

        if (UCP_Helpers::is_safe_managed_cache_file($file)) {
            $file_mtime = filemtime($file);
            if (false === $file_mtime) {
                return;
            }
            $modified = (int) $file_mtime;
            if (0 === $ttl || ($modified + $ttl) > time()) {
                $remaining = $ttl > 0 ? max(0, ($modified + $ttl) - time()) : YEAR_IN_SECONDS;
                $this->serve_cached_html_file($file, $modified, $remaining, 'HIT');
            }

            if (UCP_Options::get('enable_stale_cache') && $stale_ttl > 0 && ($modified + $ttl + $stale_ttl) > time()) {
                $url = UCP_Helpers::current_full_url();
                $this->queue_preload_url($url);
                header('Warning: 110 - "UltraCache served stale cache while revalidating"');
                $this->serve_cached_html_file($file, $modified, 0, 'STALE', 'public, max-age=0, must-revalidate');
            }
        }
    }

    /**
     * Keep cached HTML containing the rotating CWV beacon token within that token's
     * acceptance window. The public page cache and client max-age must expire before
     * the embedded token, including any configured stale period.
     *
     * @param string $html  Rendered response body.
     * @param int    $ttl   Fresh lifetime in seconds; zero means otherwise unlimited.
     * @param int    $stale Stale lifetime in seconds.
     * @return array{ttl:int,stale:int}
     */
    private function cap_cache_lifetime_for_embedded_cwv_token($html, $ttl, $stale) {
        $ttl = max(0, (int) $ttl);
        $stale = max(0, (int) $stale);
        if (!class_exists('UCP_CWV') || false === strpos((string) $html, 'window.UCP.cwvMonitor=')) {
            return array('ttl' => $ttl, 'stale' => $stale);
        }

        $window = max(MINUTE_IN_SECONDS, (int) UCP_CWV::TOKEN_WINDOW_SECONDS);
        $now = time();
        $expires_at = (((int) floor($now / $window)) + 2) * $window;
        $remaining = max(1, $expires_at - $now - MINUTE_IN_SECONDS);
        if (0 === $ttl || $ttl > $remaining) {
            $ttl = $remaining;
        }
        $stale = min($stale, max(0, $remaining - $ttl));

        return array('ttl' => $ttl, 'stale' => $stale);
    }

    /**
     * Build a weak validator from the cached representation's semantic content.
     *
     * The content hash prevents collisions when equal-sized generations are written within
     * the same filesystem timestamp second. Encoding remains part of the validator because
     * clients and shared caches negotiate it independently.
     */
    private function build_cache_etag($modified, $representation_size, $encoding, $content_hash = '') {
        $encoding = '' !== (string) $encoding ? (string) $encoding : 'identity';
        $content_hash = strtolower((string) $content_hash);
        if (1 === preg_match('/^[a-f0-9]{64}$/', $content_hash)) {
            return 'W/"ucp-' . substr($content_hash, 0, 32) . '-' . $encoding . '"';
        }

        return 'W/"ucp-' . dechex((int) $modified) . '-' . dechex((int) $representation_size) . '-' . $encoding . '"';
    }

    /**
     * A cached error response must retain its status and may not be converted into a 304.
     */
    private function cached_status_allows_not_modified($status_code) {
        return 200 === (int) $status_code;
    }

    /**
     * Shared-cache dimensions used by the page-cache key.
     *
     * @param bool $private_user_cache Whether the response belongs to one logged-in user.
     * @return string
     */
    private function page_cache_vary_header($private_user_cache = false) {
        return UCP_Cache_Policy::html_vary_header((bool) $private_user_cache);
    }

    /**
     * Build the public HTML Cache-Control header without exposing the disk-cache
     * lifetime as browser freshness. Browsers must revalidate; an optional edge
     * cache receives its own bounded s-maxage value.
     *
     * @param int  $remaining    Remaining origin/disk lifetime.
     * @param bool $allow_shared Whether shared edge caching is safe for this response.
     * @return string
     */
    private function public_html_cache_control($remaining, $allow_shared = true) {
        return UCP_Cache_Policy::public_html_cache_control($remaining, (bool) $allow_shared);
    }

    /**
     * Emit shared-cache-only headers. stale-* is intentionally kept out of the
     * browser Cache-Control header so a private browser cache cannot hide purges.
     *
     * @param int  $remaining    Remaining origin/disk lifetime.
     * @param bool $allow_shared Whether shared edge caching is safe for this response.
     * @return void
     */
    private function send_shared_html_cache_headers($remaining, $allow_shared = true) {
        $shared = UCP_Cache_Policy::shared_html_cache_control($remaining, (bool) $allow_shared);
        if ('' === $shared) {
            return;
        }
        header('CDN-Cache-Control: ' . $shared, true);
        header('Cloudflare-CDN-Cache-Control: ' . $shared, true);
    }

    private function serve_cached_html_file($file, $modified, $remaining, $status = 'HIT', $cache_control = '') {
        $file = (string) $file;
        if (!UCP_Helpers::is_safe_managed_cache_file($file)) {
            return;
        }
        $size = filesize($file);
        if (false === $size || $size <= 0 || headers_sent()) {
            return;
        }

        $accept_encoding = strtolower(UCP_Helpers::server_value('HTTP_ACCEPT_ENCODING', '', 8192));
        $representation_file = $file;
        $representation_size = $size;
        $representation_encoding = '';
        $variant_candidates = array();
        $br_quality = $this->request_allows_brotli_cache_variant() ? $this->request_encoding_quality($accept_encoding, 'br') : 0.0;
        $gzip_quality = $this->request_encoding_quality($accept_encoding, 'gzip');
        $identity_quality = $this->request_identity_quality($accept_encoding);
        if ($br_quality > 0.0) {
            $variant_candidates['br'] = array('path' => $file . '.br', 'quality' => $br_quality, 'priority' => 2);
        }
        if ($gzip_quality > 0.0) {
            $variant_candidates['gzip'] = array('path' => $file . '.gz', 'quality' => $gzip_quality, 'priority' => 1);
        }
        if ($identity_quality > 0.0) {
            $variant_candidates['identity'] = array('path' => $file, 'quality' => $identity_quality, 'priority' => 0);
        }
        uasort($variant_candidates, function ($left, $right) {
            if ($left['quality'] === $right['quality']) {
                return $right['priority'] <=> $left['priority'];
            }
            return $right['quality'] <=> $left['quality'];
        });
        foreach ($variant_candidates as $encoding => $candidate_data) {
            $candidate = $candidate_data['path'];
            if (!UCP_Helpers::is_safe_managed_cache_file($candidate)) {
                continue;
            }
            $candidate_mtime = filemtime($candidate);
            $candidate_size = filesize($candidate);
            // Never serve a compressed sibling from an older cache generation.
            if (false === $candidate_mtime || $candidate_mtime < (int) $modified || false === $candidate_size || $candidate_size <= 0) {
                continue;
            }
            $representation_file = $candidate;
            $representation_size = $candidate_size;
            $representation_encoding = 'identity' === $encoding ? '' : $encoding;
            break;
        }

        // Do not fall back to identity when the client explicitly refused it and
        // every acceptable compressed sibling was unavailable or stale.
        if ('' === $representation_encoding && $identity_quality <= 0.0) {
            return;
        }

        $content_type = 'text/html; charset=' . get_bloginfo('charset');
        $cached_status = 200;
        $content_hash = '';
        $cached_response_headers = array();
        $meta_file = $file . '.meta.json';
        if (UCP_Helpers::is_safe_managed_cache_file($meta_file)) {
            $meta = UCP_Helpers::safe_json_decode(UCP_Helpers::read_file($meta_file, 64 * KB_IN_BYTES), true);
            if (is_array($meta) && array_key_exists('content_type', $meta)) {
                $normalized_content_type = UCP_Cache_Policy::normalize_page_cache_content_type((string) $meta['content_type'], true);
                if ('' === $normalized_content_type) {
                    return;
                }
                $content_type = $normalized_content_type;
            }
            if (is_array($meta) && array_key_exists('status_code', $meta)) {
                $cached_status = $meta['status_code'];
                if (!UCP_Cache_Policy::response_status_is_page_cacheable($cached_status)) {
                    return;
                }
                $cached_status = (int) $cached_status;
            }
            if (is_array($meta) && !empty($meta['content_sha256']) && 1 === preg_match('/^[a-f0-9]{64}$/i', (string) $meta['content_sha256'])) {
                $content_hash = strtolower((string) $meta['content_sha256']);
            }
            if (is_array($meta) && !empty($meta['response_headers']) && is_array($meta['response_headers'])) {
                $cached_response_headers = $this->normalize_page_cache_response_headers($meta['response_headers']);
            }
        }

        $etag = $this->build_cache_etag($modified, $representation_size, $representation_encoding, $content_hash);
        $last_modified_hdr = gmdate('D, d M Y H:i:s', (int) $modified) . ' GMT';
        $private_user_cache = function_exists('is_user_logged_in') && is_user_logged_in();
        $cache_control = $private_user_cache
            ? 'private, no-store, max-age=0'
            : ('' !== (string) $cache_control ? (string) $cache_control : $this->public_html_cache_control($remaining, 'STALE' !== $status));
        $vary_header = $this->page_cache_vary_header($private_user_cache);
        $method = UCP_Helpers::request_method();
        if ('' === $method) {
            return;
        }
        $is_head = 'HEAD' === $method;

        if (!$private_user_cache && 'STALE' !== $status && $this->cached_status_allows_not_modified($cached_status) && $this->request_etag_matches($etag, $modified)) {
            $this->send_cached_page_response_headers($cached_response_headers);
            header('X-UltraCache: HIT-304');
            header('ETag: ' . $etag);
            header('Last-Modified: ' . $last_modified_hdr);
            header('Cache-Control: ' . $cache_control);
            $this->send_shared_html_cache_headers($remaining, 'STALE' !== $status);
            header('Vary: ' . $vary_header);
            if ('' !== $representation_encoding) {
                header('Content-Encoding: ' . $representation_encoding);
            }
            http_response_code(304);
            UCP_Diagnostics::record('cache', '304 Not Modified', array('file' => basename($file)));
            if (class_exists('UCP_Cache_Insights')) {
                UCP_Cache_Insights::record_request('HIT-304');
            }
            exit;
        }

        $this->send_cached_page_response_headers($cached_response_headers);
        header('X-UltraCache: ' . $status);
        header('Cache-Control: ' . $cache_control);
        if (!$private_user_cache) {
            $this->send_shared_html_cache_headers($remaining, 'STALE' !== $status);
            header('ETag: ' . $etag);
            header('Last-Modified: ' . $last_modified_hdr);
        }
        header('Vary: ' . $vary_header);
        header('X-UltraCache-Age: ' . (int)(time() - (int) $modified));
        if (200 !== $cached_status) {
            if (function_exists('status_header')) {
                status_header($cached_status);
            } else {
                http_response_code($cached_status);
            }
        }
        header('Content-Type: ' . $content_type);
        if (class_exists('UCP_Cache_Insights')) {
            UCP_Cache_Insights::record_request($status, '', array('age' => max(0, time() - (int) $modified)));
        }

        if ($this->is_internal_light_preload_request()) {
            header('X-UltraCache-Light-Preload: 1');
            header_remove('Content-Encoding');
            header('Content-Length: 0', true);
            UCP_Diagnostics::record('cache', 'Served bodyless cached response for internal light preload', array('file' => basename($file), 'path' => 'php_fallback'));
            exit;
        }

        if ('' !== $representation_encoding) {
            header('Content-Encoding: ' . $representation_encoding);
            header('Content-Length: ' . (int) $representation_size);
            UCP_Diagnostics::record('cache', 'Served cached response', array('file' => basename($file), 'encoding' => $representation_encoding, 'path' => 'php_fallback'));
            if (!$is_head) {
                readfile($representation_file); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped, WordPress.WP.AlternativeFunctions -- pre-compressed cached HTML streamed to the client.
            }
            exit;
        }

        // No on-the-fly compression on cache hits. .gz/.br variants are generated
        // at cache-write time, so misses pay the compression cost once and hits stay cheap.

        header('Content-Length: ' . (int) $size);
        UCP_Diagnostics::record('cache', 'Served cached response', array('file' => basename($file), 'path' => 'php_fallback'));
        if (!$is_head) {
            readfile($file); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped, WordPress.WP.AlternativeFunctions -- cached HTML streamed to the client.
        }
        exit;
    }

    private function request_encoding_quality($header, $encoding) {
        $header = strtolower(trim((string) $header));
        $encoding = strtolower(trim((string) $encoding));
        if ('' === $header || '' === $encoding) {
            return 0.0;
        }

        $exact_quality = null;
        $wildcard_quality = null;
        foreach (explode(',', $header) as $item) {
            $segments = array_map('trim', explode(';', $item));
            $coding = array_shift($segments);
            if ('' === $coding) {
                continue;
            }

            $quality = 1.0;
            foreach ($segments as $parameter) {
                if (!preg_match('/^q\s*=/i', $parameter)) {
                    continue;
                }
                if (preg_match('/^q\s*=\s*(0(?:\.\d{0,3})?|1(?:\.0{0,3})?)$/i', $parameter, $match)) {
                    $quality = (float) $match[1];
                } else {
                    $quality = 0.0;
                }
                break;
            }

            if ($coding === $encoding) {
                $exact_quality = null === $exact_quality ? $quality : max($exact_quality, $quality);
            } elseif ('*' === $coding) {
                $wildcard_quality = null === $wildcard_quality ? $quality : max($wildcard_quality, $quality);
            }
        }

        return null !== $exact_quality ? $exact_quality : (null !== $wildcard_quality ? $wildcard_quality : 0.0);
    }

    /**
     * Return the quality of the unencoded representation. Identity is acceptable
     * by default unless an exact identity range or a wildcard explicitly excludes it.
     *
     * @param string $header Accept-Encoding header value.
     * @return float
     */
    private function request_identity_quality($header) {
        $header = strtolower(trim((string) $header));
        if ('' === $header) {
            return 1.0;
        }

        $identity_quality = null;
        $wildcard_quality = null;
        foreach (explode(',', $header) as $item) {
            $segments = array_map('trim', explode(';', $item));
            $coding = array_shift($segments);
            if ('' === $coding) {
                continue;
            }

            $quality = 1.0;
            foreach ($segments as $parameter) {
                if (!preg_match('/^q\s*=/i', (string) $parameter)) {
                    continue;
                }
                if (preg_match('/^q\s*=\s*(0(?:\.\d{0,3})?|1(?:\.0{0,3})?)$/i', (string) $parameter, $match)) {
                    $quality = (float) $match[1];
                } else {
                    $quality = 0.0;
                }
                break;
            }

            if ('identity' === $coding) {
                $identity_quality = null === $identity_quality ? $quality : max($identity_quality, $quality);
            } elseif ('*' === $coding) {
                $wildcard_quality = null === $wildcard_quality ? $quality : max($wildcard_quality, $quality);
            }
        }

        if (null !== $identity_quality) {
            return $identity_quality;
        }
        return null !== $wildcard_quality && $wildcard_quality <= 0.0 ? 0.0 : 1.0;
    }

    private function request_etag_matches($etag, $modified) {
        $etag = trim((string) $etag);
        $normalized_etag = 0 === strncmp($etag, 'W/', 2) ? substr($etag, 2) : $etag;
        $ifnm = UCP_Helpers::server_value('HTTP_IF_NONE_MATCH', '', 8192);
        if ('' !== $ifnm) {
            if ('*' === trim($ifnm)) {
                return true;
            }
            foreach (explode(',', $ifnm) as $candidate) {
                $candidate = trim($candidate);
                if (0 === strncmp($candidate, 'W/', 2)) {
                    $candidate = substr($candidate, 2);
                }
                if ($candidate === $normalized_etag) {
                    return true;
                }
            }
            // RFC conditional precedence: If-Modified-Since must be ignored whenever
            // If-None-Match is present, even when none of its validators matched.
            return false;
        }
        $ifms = UCP_Helpers::server_value('HTTP_IF_MODIFIED_SINCE', '', 256);
        return '' !== $ifms && strtotime($ifms) >= (int) $modified;
    }

    public function start_buffering() {
        if (class_exists('UCP_LiteSpeed_Cache') && UCP_LiteSpeed_Cache::should_bypass_disk_page_cache()) {
            return;
        }

        if (!$this->can_cache_request()) {
            $this->maybe_send_cache_debug_header('bypass', $this->bypass_reason);
            return;
        }
        $this->maybe_send_cache_debug_header('miss');
        ob_start(array($this, 'store_buffer'));
    }

    public function store_buffer($html) {
        if (!is_string($html) || '' === trim($html)) {
            return $html;
        }

        $uncacheable = $this->response_uncacheable_details();
        $respect_upstream_no_cache = (bool) apply_filters('ucp_respect_response_no_cache_headers', true);
        $status_code = function_exists('http_response_code') ? (int) http_response_code() : 200;

        // Note: never persist error/redirect responses as page-cache HTML. A host can return a normal-looking body with HTTP 500.
        $policy = $this->cache_policy_decision(UCP_Options::get_all());
        $explicit_status_cache = 404 === $status_code && !empty($policy['matched']) && 'cache' === $policy['action'] && 'status' === $policy['scope'];
        if (!UCP_Cache_Policy::response_status_is_page_cacheable($status_code) || (404 === $status_code && !$explicit_status_cache)) {
            UCP_Diagnostics::record('cache', 'Skipped writing cache file because response status is not cacheable', array('status' => $status_code));
            return $html;
        }

        if ((defined('DONOTCACHEPAGE') && DONOTCACHEPAGE) || (function_exists('post_password_required') && post_password_required())) {
            UCP_Diagnostics::record('cache', 'Skipped writing cache file because WordPress marked the page uncacheable', array(
                'reason' => defined('DONOTCACHEPAGE') && DONOTCACHEPAGE ? 'donotcachepage' : 'password_protected',
            ));
            return $html;
        }

        if (!empty($uncacheable['blocked'])
            && ('response_cache_control' !== $uncacheable['reason']
                || $respect_upstream_no_cache
                || !empty($uncacheable['unconditional']))) {
            UCP_Diagnostics::record('cache', 'Skipped writing cache file because response is marked private or uncacheable', $uncacheable);
            return $html;
        }

        if (!empty($uncacheable['blocked']) && 'response_cache_control' === $uncacheable['reason']) {
            UCP_Diagnostics::record('cache', 'Ignored upstream no-cache response header for an otherwise cacheable public page', $uncacheable);
            if (!headers_sent()) {
                header_remove('Cache-Control');
                header_remove('Pragma');
                header_remove('Expires');
            }
        }

        if (empty($uncacheable['blocked']) && !empty($uncacheable['reason']) && 'response_set_cookie_ignored' === $uncacheable['reason']) {
            UCP_Diagnostics::record('cache', 'Ignored cache-safe Set-Cookie header for an otherwise cacheable public page', array(
                'safe_cookies' => isset($uncacheable['safe_cookies']) ? $uncacheable['safe_cookies'] : array(),
                'unknown_cookies' => isset($uncacheable['unknown_cookies']) ? $uncacheable['unknown_cookies'] : array(),
            ));
        }

        $current_url = UCP_Helpers::enforce_local_url(UCP_Helpers::current_full_url());
        $ttl = isset($policy['ttl']) ? absint($policy['ttl']) : absint(UCP_Options::get('cache_lifespan', 10)) * HOUR_IN_SECONDS;
        $stale_ttl = isset($policy['stale']) ? absint($policy['stale']) : 0;
        $cache_lifetime = $this->cap_cache_lifetime_for_embedded_cwv_token($html, $ttl, $stale_ttl);
        $ttl = $cache_lifetime['ttl'];
        $stale_ttl = $cache_lifetime['stale'];
        $private_lifetime = $this->cap_private_user_cache_lifetime($ttl, $stale_ttl);
        $ttl = $private_lifetime['ttl'];
        $stale_ttl = $private_lifetime['stale'];
        $cache_path = UCP_Helpers::cache_file_path($current_url);
        $is_feed_policy = !empty($policy['matched']) && 'cache' === $policy['action'] && 'feed' === $policy['scope'];
        $content_type = UCP_Cache_Policy::normalize_page_cache_content_type('text/html; charset=' . get_bloginfo('charset'), $is_feed_policy);
        $content_type_headers = array();
        foreach (headers_list() as $response_header) {
            if (0 === stripos((string) $response_header, 'Content-Type:')) {
                $content_type_headers[] = trim(substr((string) $response_header, strlen('Content-Type:')));
            }
        }
        if (count($content_type_headers) > 1) {
            UCP_Diagnostics::record('cache', 'Skipped writing cache file because multiple Content-Type headers were present');
            return $html;
        }
        if (1 === count($content_type_headers)) {
            $content_type = UCP_Cache_Policy::normalize_page_cache_content_type($content_type_headers[0], $is_feed_policy);
        }
        $content_type_base = strtolower(trim((string) strtok($content_type, ';')));
        if ('' === $content_type) {
            UCP_Diagnostics::record('cache', 'Skipped writing cache file because the response content type is not page-cacheable', array(
                'content_type' => $content_type_base,
                'policy' => $is_feed_policy ? 'feed' : 'page',
            ));
            return $html;
        }

        if (!UCP_Cache_Policy::response_body_is_complete($html, $content_type)) {
            UCP_Diagnostics::record('cache', 'Skipped writing cache file because the HTML document appears incomplete', array('status' => $status_code));
            return $html;
        }
        $written = $this->write_cache_representation($cache_path, $html, array(
            'content_type'     => $content_type,
            'status_code'      => $status_code,
            'ttl'              => $ttl,
            'stale'            => $stale_ttl,
            'response_headers' => $this->capture_page_cache_response_headers(),
        ));
        if (!$written) {
            UCP_Diagnostics::record('cache', 'Failed writing cache file', array('url' => $current_url, 'path' => UCP_Helpers::cache_file_path($current_url)));
            return $html;
        }
        if (class_exists('UCP_Cache_Tags') && UCP_Cache_Tags::enabled()
            && !UCP_Cache_Tags::register_url($current_url, UCP_Cache_Tags::current_request_tags())) {
            foreach (array($cache_path, $cache_path . '.gz', $cache_path . '.br', $cache_path . '.meta.json') as $cache_file) {
                UCP_Helpers::safe_delete_file($cache_file);
            }
            UCP_Diagnostics::record('cache', 'Discarded cache file because cache-tag metadata could not be persisted', array('url' => $current_url));
            return $html;
        }
        if ('text/html' === strtolower(substr($content_type, 0, 9)) && (empty($policy['matched']) || !in_array($policy['scope'], array('feed', 'status'), true))) {
            $this->write_direct_cache_mirror($current_url, $html, $ttl, $stale_ttl);
        }
        UCP_Diagnostics::record('cache', 'Stored fresh cache file', array('url' => $current_url, 'file' => basename($cache_path)));
        if (class_exists('UCP_Cache_Insights')) {
            UCP_Cache_Insights::record_request('MISS', '', array('ttl' => $ttl, 'policy' => !empty($policy['matched']) ? $policy['scope'] : 'default'));
        }
        if (!headers_sent()) {
            $response_ttl = $ttl > 0 ? $ttl : YEAR_IN_SECONDS;
            $private_user_cache = function_exists('is_user_logged_in') && is_user_logged_in();
            header('X-UltraCache: MISS');
            header('Cache-Control: ' . ($private_user_cache ? 'private, no-store, max-age=0' : $this->public_html_cache_control($response_ttl, true)));
            if (!$private_user_cache) {
                $this->send_shared_html_cache_headers($response_ttl, true);
            }
            header('Vary: ' . $this->page_cache_vary_header($private_user_cache));
            if ($this->is_internal_light_preload_request()) {
                header('X-UltraCache-Light-Preload: 1');
                header_remove('Content-Encoding');
                header('Content-Length: 0', true);
                return '';
            }
        }
        return $html;
    }


    /**
     * Queue optional compressed derivatives outside the cache-miss request path.
     *
     * @param string $path            Absolute managed cache path.
     * @param string $content_sha256  Identity generation hash.
     * @return bool True only when a durable queue job was created.
     */
    private function queue_precompressed_cache_variants($path, $content_sha256) {
        if (!class_exists('UCP_Jobs') || !method_exists('UCP_Jobs', 'enqueue_unique')) {
            return false;
        }

        $root = trailingslashit(wp_normalize_path(UCP_CACHE_DIR));
        $normalized_path = wp_normalize_path((string) $path);
        if (0 !== strpos($normalized_path, $root)) {
            return false;
        }
        $relative_path = ltrim(substr($normalized_path, strlen($root)), '/');
        if ('' === $relative_path
            || strlen($relative_path) > 500
            || false !== strpos($relative_path, "\0")
            || in_array('..', explode('/', $relative_path), true)
            || 1 !== preg_match('/\.(?:html?|xhtml)$/i', $relative_path)
            || 1 !== preg_match('/^[a-f0-9]{64}$/D', (string) $content_sha256)) {
            return false;
        }

        $payload = array(
            'relative_path'  => $relative_path,
            'content_sha256' => (string) $content_sha256,
        );
        $queued = UCP_Jobs::enqueue_unique('precompress_cache', $payload, 25, 'cache');
        if ($queued) {
            return true;
        }

        // enqueue_unique() historically returns false both for duplicates and for
        // database failures. An existing durable job is success for this caller;
        // only a real queue failure should fall back to synchronous compression.
        return method_exists('UCP_Jobs', 'unique_job_exists')
            && UCP_Jobs::unique_job_exists('precompress_cache', $payload, 'cache');
    }

    /**
     * Execute one content-bound precompression job.
     *
     * Public only so the internal queue runner can invoke it on a constructor-free
     * cache instance. The relative path and expected hash are both validated.
     *
     * @param string $relative_path  Path relative to UCP_CACHE_DIR.
     * @param string $expected_hash Expected SHA-256 of the identity representation.
     * @return bool True for a completed or safely skipped stale job.
     */
    public function precompress_cache_representation($relative_path, $expected_hash) {
        $relative_path = ltrim(wp_normalize_path((string) $relative_path), '/');
        $expected_hash = strtolower(trim((string) $expected_hash));
        if ('' === $relative_path
            || strlen($relative_path) > 500
            || false !== strpos($relative_path, "\0")
            || in_array('..', explode('/', $relative_path), true)
            || 1 !== preg_match('/\.(?:html?|xhtml)$/i', $relative_path)
            || 1 !== preg_match('/^[a-f0-9]{64}$/D', $expected_hash)) {
            return false;
        }

        $path = trailingslashit(UCP_CACHE_DIR) . $relative_path;
        if (!UCP_Helpers::is_safe_managed_cache_file($path)) {
            return false;
        }

        // Serialize derivative generation with identity publication. Without this lock,
        // an older job could validate generation A, compress it, and publish its output
        // after generation B had already replaced the identity file.
        $lock = $this->acquire_cache_write_lock($path);
        if (!is_resource($lock)) {
            return false;
        }

        try {
            // Recheck after locking to close the path/readability TOCTOU window.
            if (!UCP_Helpers::is_safe_managed_cache_file($path) || !is_readable($path)) {
                return false;
            }

            $max_size = max(64 * KB_IN_BYTES, min(10 * MB_IN_BYTES, absint(apply_filters('ucp_precompression_max_input_bytes', 2 * MB_IN_BYTES, $path))));
            $size = filesize($path);
            if (false === $size || $size < 860 || $size > $max_size) {
                UCP_Helpers::safe_delete_file($path . '.gz');
                UCP_Helpers::safe_delete_file($path . '.br');
                return true;
            }

            $html = UCP_Helpers::read_file($path, $max_size + 1);
            if (!is_string($html) || strlen($html) !== (int) $size) {
                return false;
            }
            if (!hash_equals($expected_hash, hash('sha256', $html))) {
                // A newer cache generation replaced this job's input. Do not create
                // derivatives for stale content; the newer generation has its own job.
                return true;
            }

            $this->write_precompressed_cache_variants($path, $html);
            return true;
        } catch (Throwable $e) {
            UCP_Helpers::safe_delete_file($path . '.gz');
            UCP_Helpers::safe_delete_file($path . '.br');
            if (class_exists('UCP_Diagnostics')) {
                UCP_Diagnostics::record('cache', 'Queued cache precompression failed safely.', array(
                    'path_hash' => hash('sha256', wp_normalize_path($path)),
                    'exception' => sanitize_key(get_class($e)),
                    'code'      => (string) $e->getCode(),
                ));
            }
            return false;
        } finally {
            $this->release_cache_write_lock($lock);
        }
    }

    private function write_precompressed_cache_variants($path, $html) {
        $path = (string) $path;
        $html = (string) $html;
        if ('' === $path) {
            return;
        }

        $brotli_path = $path . '.br';
        $gzip_path   = $path . '.gz';
        $html_size   = strlen($html);
        $max_size = max(64 * KB_IN_BYTES, min(10 * MB_IN_BYTES, absint(apply_filters('ucp_precompression_max_input_bytes', 2 * MB_IN_BYTES, $path))));
        if ($html_size < 860 || $html_size > $max_size) {
            UCP_Helpers::safe_delete_file($brotli_path);
            UCP_Helpers::safe_delete_file($gzip_path);
            return;
        }

        // Moderate defaults avoid turning a cold cache miss into a CPU spike. Hosts can
        // raise these levels explicitly when precompression runs outside the request path.
        $brotli_level = max(0, min(11, absint(apply_filters('ucp_brotli_precompression_level', 4))));
        $gzip_level   = max(1, min(9, absint(apply_filters('ucp_gzip_precompression_level', 6))));

        if (UCP_Options::get('enable_brotli_precompression') && function_exists('brotli_compress')) {
            try {
                $br = brotli_compress($html, $brotli_level);
            } catch (\Throwable $e) {
                $br = false;
                UCP_Diagnostics::record('cache', 'Brotli precompression failed', array(
                    'exception' => sanitize_key(get_class($e)),
                    'code'      => (string) $e->getCode(),
                ));
            }
            if (is_string($br) && '' !== $br && strlen($br) < $html_size) {
                if (!UCP_Helpers::write_file_atomic($brotli_path, $br)) {
                    UCP_Helpers::safe_delete_file($brotli_path);
                    UCP_Diagnostics::record('cache', 'Failed writing Brotli cache variant', array('file' => basename($brotli_path)));
                }
            } else {
                UCP_Helpers::safe_delete_file($brotli_path);
            }
        } else {
            UCP_Helpers::safe_delete_file($brotli_path);
        }

        if (UCP_Options::get('enable_gzip_precompression') && function_exists('gzencode')) {
            try {
                $gz = gzencode($html, $gzip_level);
            } catch (\Throwable $e) {
                $gz = false;
                UCP_Diagnostics::record('cache', 'Gzip precompression failed', array(
                    'exception' => sanitize_key(get_class($e)),
                    'code'      => (string) $e->getCode(),
                ));
            }
            if (is_string($gz) && '' !== $gz && strlen($gz) < $html_size) {
                if (!UCP_Helpers::write_file_atomic($gzip_path, $gz)) {
                    UCP_Helpers::safe_delete_file($gzip_path);
                    UCP_Diagnostics::record('cache', 'Failed writing Gzip cache variant', array('file' => basename($gzip_path)));
                }
            } else {
                UCP_Helpers::safe_delete_file($gzip_path);
            }
        } else {
            UCP_Helpers::safe_delete_file($gzip_path);
        }
    }

    private function request_allows_brotli_cache_variant() {
        // Prefer the canonical WordPress origin. X-Forwarded-Proto is not a safe
        // trust signal at plugin level because proxy trust is configured by the host.
        $home_scheme = strtolower((string) wp_parse_url(home_url('/'), PHP_URL_SCHEME));
        if ('https' === $home_scheme) {
            return true;
        }
        if (function_exists('is_ssl') && is_ssl()) {
            return true;
        }
        $https = strtolower(UCP_Helpers::server_value('HTTPS', '', 16));
        return in_array($https, array('on', '1'), true);
    }

    private function write_direct_cache_mirror($url, $html, $ttl = null, $stale = null) {
        if ((function_exists('is_multisite') && is_multisite())
            || UCP_Options::get('enable_cache_policy_rules')
            || UCP_Options::get('block_unknown_request_cookies')
            || !empty(UCP_Helpers::normalize_multiline(UCP_Options::get('exclude_user_agents', '')))) {
            return;
        }
        if (!is_string($html) || '' === trim($html)) {
            return;
        }
        if ('guest' !== UCP_Helpers::user_state_suffix()) {
            return;
        }
        $parts = wp_parse_url((string) $url);
        if (!empty($parts['query'])) {
            return;
        }
        $path = UCP_Helpers::direct_cache_file_path($url);
        if ('' === $path) {
            return;
        }
        $this->write_cache_representation($path, $html, array(
            'content_type' => 'text/html; charset=' . get_bloginfo('charset'),
            'status_code'  => 200,
            'ttl'          => null === $ttl ? absint(UCP_Options::get('cache_lifespan', 10)) * HOUR_IN_SECONDS : max(0, (int) $ttl),
            'stale'        => null === $stale ? absint(UCP_Options::get('stale_cache_lifespan', 24)) * HOUR_IN_SECONDS : max(0, (int) $stale),
        ));
    }

    protected function queue_preload_url($url) {
        if (!$url || !class_exists('UCP_Jobs') || !UCP_Options::get('enable_preload') || !UCP_Options::get('enable_preload_queue')) {
            return;
        }
        $url = UCP_Helpers::strict_local_url($url);
        if (!$url || !wp_http_validate_url($url)) {
            return;
        }
        UCP_Jobs::enqueue_unique('preload_url', array('url' => $url), 15, 'preload');
    }

}
