<?php
if (!defined('ABSPATH')) {
    exit;
}
?>
        <section class="ucp-panel full ucp-panel--asset-unloads-live">
            <div class="ucp-panel__header"><div><h2><?php esc_html_e('Bestanden uitzetten', 'ultracache-pro'); ?></h2><p><?php esc_html_e('Gebruik dit alleen voor handles die je echt herkent.', 'ultracache-pro'); ?></p></div></div>
            <div class="ucp-field-row ucp-field-row--2 ucp-assets-grid-live">
                <label class="ucp-field"><span><?php esc_html_e('Deze stijlbestanden overal uitzetten', 'ultracache-pro'); ?></span><textarea name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[disabled_style_handles]" rows="6"><?php echo esc_textarea($settings['disabled_style_handles']); ?></textarea><small><?php esc_html_e('Eén handle per regel. Voorbeeld: contact-form-7', 'ultracache-pro'); ?></small></label>
                <label class="ucp-field"><span><?php esc_html_e('Deze scriptbestanden overal uitzetten', 'ultracache-pro'); ?></span><textarea name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[disabled_script_handles]" rows="6"><?php echo esc_textarea($settings['disabled_script_handles']); ?></textarea><small><?php esc_html_e('Eén handle per regel. Voorbeeld: wc-cart-fragments', 'ultracache-pro'); ?></small></label>
                <label class="ucp-field"><span><?php esc_html_e('Stijlbestanden per pagina uitzetten', 'ultracache-pro'); ?></span><textarea name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[conditional_style_unloads]" rows="6"><?php echo esc_textarea(isset($settings['conditional_style_unloads']) ? $settings['conditional_style_unloads'] : ''); ?></textarea><small><?php esc_html_e('Eén regel per keer. Voorbeeld: /afrekenen/ => theme-checkout', 'ultracache-pro'); ?></small></label>
                <label class="ucp-field"><span><?php esc_html_e('Scriptbestanden per pagina uitzetten', 'ultracache-pro'); ?></span><textarea name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[conditional_script_unloads]" rows="6"><?php echo esc_textarea(isset($settings['conditional_script_unloads']) ? $settings['conditional_script_unloads'] : ''); ?></textarea><small><?php esc_html_e('Eén regel per keer. Voorbeeld: /account/ => reviews-loader', 'ultracache-pro'); ?></small></label>
                <label class="ucp-field"><span><?php esc_html_e('Asset Manager 2.0 regels', 'ultracache-pro'); ?></span><textarea name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[advanced_asset_rules]" rows="8"><?php echo esc_textarea(isset($settings['advanced_asset_rules']) ? $settings['advanced_asset_rules'] : ''); ?></textarea><small><?php esc_html_e('Formaat: script|handle|disable|path_contains|/contact/ of style|handle|keep|post_type|product. Scopes: all, path_contains, url_contains, post_type, archive, device, logged_in, logged_out, regex, front_page, singular, 404.', 'ultracache-pro'); ?></small></label>
                <label class="ucp-field ucp-checkbox"><input type="hidden" name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[enable_asset_test_mode]" value="0"><input type="checkbox" role="switch" name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[enable_asset_test_mode]" value="1" <?php checked(!empty($settings['enable_asset_test_mode'])); ?>><span class="ucp-checkbox__text"><span class="ucp-checkbox__label"><?php esc_html_e('Asset Manager testmodus', 'ultracache-pro'); ?></span><span class="ucp-checkbox__help"><?php esc_html_e('Past asset-regels alleen toe voor beheerders, zodat bezoekers nog de normale site zien.', 'ultracache-pro'); ?></span></span></label>
                <label class="ucp-field ucp-checkbox"><input type="hidden" name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[enable_asset_manager_snapshot]" value="0"><input type="checkbox" role="switch" name="<?php echo esc_attr(UCP_Options::OPTION_KEY); ?>[enable_asset_manager_snapshot]" value="1" <?php checked(!empty($settings['enable_asset_manager_snapshot'])); ?>><span class="ucp-checkbox__text"><span class="ucp-checkbox__label"><?php esc_html_e('Frontend asset-inspector voor admins', 'ultracache-pro'); ?></span><span class="ucp-checkbox__help"><?php esc_html_e('Slaat de laatst bezochte frontend-assets op voor het assetoverzicht. Alleen voor beheerders.', 'ultracache-pro'); ?></span></span></label>
            </div>
        </section>
